package com.samples.pck.spring.rest.service;

import java.util.Date;

import javax.transaction.Transactional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.samples.pck.spring.rest.dao.UsersRepository;
import com.samples.pck.spring.rest.entity.Useraudit;
import com.samples.pck.spring.rest.entity.Users;

@Service
public class UsersService {

	@Autowired
	UsersRepository usersRepository;
	
	@Transactional
	public Users addUser(Users user) throws IllegalAccessException {
		if(user.getUserId() != null) 
			throw new IllegalAccessException("You cannot add a user with the id, this field is autogenerated!");
		
		return usersRepository.save(user);
	}
	
	@Transactional
	public Users updateUser(Users user) throws IllegalAccessException{
		if(user.getUserId() == null) 
			throw new IllegalAccessException("Illegal Access! User id required!!");
		
		return usersRepository.save(user);
	}
	
	public Users getUserById(Long userId) {		
		return usersRepository.findById(userId).get();
	}
	
	@Transactional
	public boolean delete(Users user) {
		usersRepository.delete(user);
		return true;
	}
	
}
